/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const LucideEye: typeof import('~icons/lucide/eye')['default']
  const LucideLock: typeof import('~icons/lucide/lock')['default']
  const LucidePencil: typeof import('~icons/lucide/pencil')['default']
  const LucideTrash: typeof import('~icons/lucide/trash')['default']
  const LucideUpload: typeof import('~icons/lucide/upload')['default']
}
