/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    CommentEditor: typeof import('./src/components/CommentEditor.vue')['default']
    DocumentList: typeof import('./src/components/DocumentList.vue')['default']
    FloatingComments: typeof import('./src/components/FloatingComments.vue')['default']
    FontFamily: typeof import('./src/components/FontFamily.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    LucideBadgeCheck: typeof import('~icons/lucide/badge-check')['default']
    LucideCheck: typeof import('~icons/lucide/check')['default']
    LucideMessageCircleCode: typeof import('~icons/lucide/message-circle-code')['default']
    LucideMessageCircleReply: typeof import('~icons/lucide/message-circle-reply')['default']
    LucideX: typeof import('~icons/lucide/x')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewVersionDialog: typeof import('./src/components/NewVersionDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextEditor: typeof import('./src/components/TextEditor.vue')['default']
    ToC: typeof import('./src/components/ToC.vue')['default']
    UsersBar: typeof import('./src/components/UsersBar.vue')['default']
    VersionsSidebar: typeof import('./src/components/VersionsSidebar.vue')['default']
    WriterSettings: typeof import('./src/components/WriterSettings.vue')['default']
  }
}
